#!/bin/bash
# Credits: @jungleridamanvp
# Copyright (C) 2023 PyroSupra-Userbot
#
# This file is a part of < https://github.com/Sh6Kuro/PyroSupra-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/Sh6Kuro/PyroSupra-Userbot/blob/main/LICENSE/>.
#
# t.me/Cemarasupport & t.me/Kat4logXcode

_starter () {
    echo "Downloading source code"
    git clone https://github.com/Sh6Kuro/PyroSupra-Userbot
    cd PyroSupra-Userbot/ && rm -rf .git
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "PyroSupra-Userbot v0.2.0, Copyright © 2023 (jungleridamanvp) <https://github.com/Sh6Kuro>"
    python3 -m Sh6Project
}

_starter
